#!/bin/bash

alias rc="bundle exec rails console"
alias bi="bundle install"
alias be="bundle exec"
alias bu="bundle update"
alias bo="bundle open"
alias bc="bundle console"
alias cuke='be cucumber'
alias e='vim'
alias :q='exit'
alias gst='git status'

alias dry='cd ~/Code/drydiary.com'
alias dot='cd ~/Code/dotfiles'
alias oto='cd ~/Code/音'
alias myboxen='cd /opt/boxen/repo'
alias cov='open reports/coverage/index.html'
alias git='hub'
alias gitclean='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias nuget='mono ~/.bin/nuget.exe'
alias f='fab -f ~/Code/puppet/fabfile.py'
alias fdocs='open https://github.com/uswitch/puppet/blob/master/fabricguide.md'
alias please='sudo'
alias quietly='ssh'
alias bw='cd ~/Code/broadband-web'
alias gin="git"
